@startmindmap "Azure Container Apps Security"

title Azure Container Apps\nSecurity

' Available themes: https://plantuml.com/theme
!theme sketchy

' skinparam backgroundColor #e8edec
skinparam backgroundColor #969998
' skinparam nodeWidth 200
' skinparam nodeHeight 30

<style>
    mindMapDiagram {
        .root {
            BackgroundColor darkblue
            LineColor black
            FontColor white
        }

        .blue {
            FontColor darkblue
        }

        node {
            FontColor white
            LineColor black
            BackgroundColor black
            Shadowing 2.0
            RoundCorner 25
        }
        :depth(0) {
            FontColor black
            LineColor white
            BackgroundColor white
            Shadowing 0.0
        }
        :depth(1) {
            FontColor black
            BackgroundColor darkgrey
            Shadowing 2.0
        }

        arrow {
            LineStyle 4
            LineThickness 0.5
            LineColor green
        }

        boxless {
            FontColor black
            Margin 10
            Padding 10
            MaximumWidth 400
        }
    }
</style>

caption AuthN and AuthZ
footer Built in AuthN and AuthZ features to secure your external ingress-enabled container app with minimal or no code


+ AuthN and AuthZ\nfor Ingress-enabled\nContainer Apps <<root>>
++ Out-of-the-box auth
+++_ Only to be used with HTTPS
+++_ Disable "allowInsecure" in ingress config
+++ Federated identity providers
++++_ /.auth/login/aad
++++_ /.auth/login/facebook
++++_ /.auth/login/twitter
++++_ /.auth/login/google
++++_ /.auth/login/github
++++_ /.auth/login/____ (Open Id Connect)

++ Restrict access setting
+++_ Authenticated users only?
++++ Yes
+++++_ Require Authentication
++++ No
+++++_ Allow unauthenticated

++ Middleware component
+++_ Runs as a 
++++ Sidecar container
+++++_ Intercepts all HTTP requests
+++++ Manages...
++++++_ Provider authentication
++++++_ Authenticated session
++++++_ Identity injection into request headers
+++_ Runs in a separate container, isolated from the application code
+++ Isolated
++++_ No direct integration possible (with your code)
++++_ All info provided in
+++++ Request headers

+ Authentication flow <<root>>
++ Without provider SDK
+++_ <&flag> server-directed flow\nor server flow
++++_ Delegates federated sign-in to Container Apps
+++_ Presents the provider's
++++ sign-in page
++ With provider SDK
+++_ <&flag> client-directed flow\nor client flow
++++_ Manually signs users into the provider
+++_ Submits the
++++ auth token
+++++_ to Container Apps for validation

legend right
Middleware sidecar component runs in a seperate process
delegating authentication to to identity providers while
managing session and request header identity injection.
endlegend

@endmindmap
