@startmindmap "Azure Container Apps Secrets"
title Azure Container Apps\nSecrets

' Available themes: https://plantuml.com/theme
!theme sketchy

' skinparam backgroundColor #e8edec
skinparam backgroundColor #969998
' skinparam nodeWidth 200
' skinparam nodeHeight 30

<style>
    mindMapDiagram {
        .root {
            BackgroundColor darkblue
            LineColor black
            FontColor white
        }

        .blue {
            FontColor darkblue
        }

        node {
            FontColor white
            LineColor black
            BackgroundColor black
            Shadowing 2.0
            RoundCorner 25
        }
        :depth(0) {
            FontColor black
            LineColor white
            BackgroundColor white
            Shadowing 0.0
        }
        :depth(1) {
            FontColor black
            BackgroundColor darkgrey
            Shadowing 2.0
        }

        arrow {
            LineStyle 4
            LineThickness 0.5
            LineColor green
        }

        boxless {
            FontColor black
            Margin 10
            Padding 10
            MaximumWidth 400
        }
    }
</style>

caption Secrets
footer Secrets store sensitive configuration values at the application level.

+ Secret values

++ Availability
+++_ Container Apps
+++_ Inside scale rules

++_ trigger
+++ Application-scope changes
++++_ outside of any revision.
++++_ from...
+++++_ **properties.configuration** in ARM template

++_ do not generate new
+++ Revisions
++++_ Adding, removing, changing does not create new revisions.
++++_ Each revision can access one or more secrets.
++++_ Mutiple revisions can access the same secret(s).
++++ Secret\nReference
+++++_ Updated or deleted secrets **don't automatically affect existing revisions.**
+++++_ to ensure...
++++++_ Deploy a new revision
++++++_ Restart an existing revision
++++++ Deletion
+++++++_ Deploy new revision that no longer references the old secret.
+++++++_ Deactivate all versions that reference the secret.

++_ No support for direct...
+++ <s>Key Vault</s>
++++_ ... integration
+++_ instead enable
++++ Managed Identity
+++++_ and use
++++++ Key Vault SDK
+++++++_ to access secrets

legend right
Secrets store sensitive configuration values at the application level.
Secrets do not generate new revisions but need to be carefully managed
with new revisions (especially old secret deletions).
endlegend

@endmindmap
