@startmindmap "Azure Container Apps Secrets"
title Azure Container Apps\nSecrets

' Available themes: https://plantuml.com/theme
!theme sketchy

' skinparam backgroundColor #e8edec
skinparam backgroundColor #969998
' skinparam nodeWidth 200
' skinparam nodeHeight 30

<style>
    mindMapDiagram {
        .root {
            BackgroundColor darkblue
            LineColor black
            FontColor white
        }

        .blue {
            FontColor darkblue
        }

        node {
            FontColor white
            LineColor black
            BackgroundColor black
            Shadowing 2.0
            RoundCorner 25
        }
        :depth(0) {
            FontColor black
            LineColor white
            BackgroundColor white
            Shadowing 0.0
        }
        :depth(1) {
            FontColor black
            BackgroundColor darkgrey
            Shadowing 2.0
        }

        arrow {
            LineStyle 4
            LineThickness 0.5
            LineColor green
        }

        boxless {
            FontColor black
            Margin 10
            Padding 10
            MaximumWidth 400
        }
    }
</style>

caption Secrets
footer Secrets store sensitive configuration values at the application level.


+ Secret values
++_ trigger
+++ Application-scope changes
++_ from...
+++_ **properties.configuration** in ARM template

+ Manage secrets
++_ Securely store sensitive configuration values
++_ Secrets can be referenced by multiple revisions
++_ Updated or deleted secrets don't automatically affect existing revisions

legend right
Secrets store sensitive configuration values at the application level.
endlegend

@endmindmap
