@startmindmap "Azure Container Apps Environment"

title Azure Container Apps Environment\nOverview

caption A Secure Boundary
footer To manage related services (microservices) with or without Dapr


' List of available themes:
' https://plantuml.com/theme
!theme sketchy
'!theme carbon-gray
'!theme cyborg
'!theme mars
' skinparam backgroundColor #e8edec
skinparam backgroundColor #969998

<style>
    mindMapDiagram {
        .root {
            BackgroundColor darkblue
            LineColor black
            FontColor white
        }

        .blue {
            FontColor darkblue
        }


        node {
            FontColor white
            LineColor black
            BackgroundColor black
            Shadowing 2.0
            RoundCorner 25
        }
        :depth(0) {
            FontColor black
            LineColor white
            BackgroundColor white
            Shadowing 0.0
        }
        :depth(1) {
            FontColor black
            BackgroundColor darkgrey
            Shadowing 2.0
        }

        arrow {
            LineStyle 4
            LineThickness 0.5
            LineColor green
        }

        boxless {
            FontColor black
            Margin 10
            Padding 10
            MaximumWidth 400
        }
    }
</style>

+ Azure Container Apps\nEnvironment <<root>>
++_ Share the same
+++ Configuration
++++_ Will share the same Dapr config
+++ Virtual Network
++++ Secure Boundary
++++_ **HTTPS ingress** without managing other Azure infrastructure
++++_ **Internal ingress** and **service discovery** for secure internal-only endpoints
+++_ Monitors and writes\nto the same
++++ Azure Log Analytics

++_ provides
+++ Microservices properties
++++_ Independent
+++++ Deployment
++++++_ of related services
+++++ scaling
+++++ versioning
+++++ upgrades
++++ Service discovery
+++++_ for internal communication
++++ Dapr integration
+++++_ extra support\nfor
++++++_ Distributed function calls
++++++_ Handling failures, retries, timeouts
++++++_ Observability, pub/sub
++++++_ Service-to-service invocation\n\twith mutual TLS

++_ Microservice management via
+++ Dapr
++++_ service invocation API

--_ Use different environments if...\n...do not want...
---_ to share the same resources
---_ to communicate via\nDapr service invocation API

@endmindmap