@startmindmap "Azure Container Apps Overview"

title Azure Container Apps\nOverview

' Available themes: https://plantuml.com/theme
!theme sketchy

' skinparam backgroundColor #e8edec
skinparam backgroundColor #969998

<style>
    mindMapDiagram {
        .root {
            BackgroundColor darkblue
            LineColor black
            FontColor white
        }

        .blue {
            FontColor darkblue
        }

        node {
            FontColor white
            LineColor black
            BackgroundColor black
            Shadowing 2.0
            RoundCorner 25
        }
        :depth(0) {
            FontColor black
            LineColor white
            BackgroundColor white
            Shadowing 0.0
        }
        :depth(1) {
            FontColor black
            BackgroundColor darkgrey
            Shadowing 2.0
        }

        arrow {
            LineStyle 4
            LineThickness 0.5
            LineColor green
        }

        boxless {
            FontColor black
            Margin 10
            Padding 10
            MaximumWidth 400
        }
    }
</style>

caption Serverless container service <<blue>>
footer Built for microservice applications without the overhead of managing complex infrastructure

legend right
Used for microservice applications that require __orchestration__
...without the overhead of managing complex infrastructure
endlegend

+ Azure Container Apps <<root>>
++ Purpose
+++_ Container service
++++_ Run microservices\nand containerized applications
++++ Serverless
+++++_ Managed container orchestration
+++++_ platform over
++++++ Azure Kubernetes
+++++_ No complex infrastructure management

-- Scaling
--- Autoscaling
----_ Robust **autoscaling** capabilities
----_ Automatic restart of crashed containers


--- Dynamic scaling
----_  via any **KEDA-supported** scaler
----_ based on
-----_ HTTP traffic
-----_ Event-driven processing
-----_ <&flag> CPU or memory load <<blue>>
------_ **CANNOT**\nscale to zero <<blue>>

++++_ Support for any runtime,\nprogramming language, development stack
+++ Common uses
++++ Microservices
++++_ API endpoints
++++ Processing
+++++_ background processing, 
+++++_ event-driven processing, 

-- Limitations
---_ No privileged containers
---_ <&flag> Cannot run as root <<blue>>
--- Linux Only
----_ Linux-based (linux/amd64)\ncontainer images required




++ Traffic splitting
+++_ Blue/Green deployments and A/B testing

++ Multiple Revisions
+++_ Run multiple container revisions

++ Configuration
+++_ Manage applications with Azure CLI, Azure portal, ARM templates
+++_ Securely manage secrets directly in the application
+++_ Setup containers using properties.template in ARM templates
+++_ Array of containers for sidecar pattern

++_ Management (over virtual network) using
+++ App Service Environment
++++_ Microservices with **Dapr** integration

-- Authentication and authorization
---_ **Built-in AuthZ and AuthN**
----_ as a sidecar
---_ **No code required**
---_ Federated identity providers: Microsoft Identity Platform,\nFacebook, GitHub, Google, Twitter, Any OpenID Connect provider

-- Container registries
---_ Run containers from any registry
---- Docker Hub
---- Azure Container Registry (ACR)
---_ Deploy images from private and public registries
---_ Credentials + registry fields info in configuration

+ Requires Azure Container Apps CLI Extension to be installed

@endmindmap
