@startmindmap "Container Groups"

title Container Groups
footer Azure Container Instances

<style>
    mindMapDiagram {
        .root {
            BackgroundColor darkblue
            LineColor black
            FontColor white
        }

        node {
            FontColor white
            LineColor black
            BackgroundColor black
            Shadowing 2.0
            RoundCorner 25
        }
        :depth(0) {
            FontColor black
            LineColor white
            BackgroundColor white
            Shadowing 0.0
        }
        :depth(1) {
            FontColor black
            BackgroundColor darkgrey
            Shadowing 2.0
        }

        arrow {
            LineStyle 4
            LineThickness 0.5
            LineColor green
        }

        boxless {
            FontColor black
            Margin 10
            Padding 10
            MaximumWidth 400
        }
    }
</style>

+ Container groups <<root>>

--_ Similar to a
--- Kubernetes Pod
--_ Collection of containers...\n ...scheduled on the same host machine

++_ Share lifecycle, resources,\nlocal network, storage volumes
+++ Network
++++_ Assigned a single DNS name label\n...and public IP address
++++_ Exposes one or more **ports**\n(from one or more container instances)
++++_ Communicate with each other using
+++++ localhost
++++_ Port mapping not supported
+++++_ share same port namespace


+++ Volume mounts 
++++_ Secrets
++++_ Empty directory
++++_ Cloned Git repo
++++ Azure File shares
+++++_ are
++++++_  fully managed...\nuse Server Message Block (SMB) protocol
++++++_ also used with VMs
+++++_ limited to...
++++++_ Linux containers only
++++++_ Container must **run as root**
++++++_ CIFS support
++++ MUST deploy using
+++++_ ARM Template
+++++_ YAML file



+++ Multi-container Groups
++++ Deployment
+++++_ **Resource Manager (ARM) template**\n...deploy extra resources\neg. Azure Files share
+++++_ **YAML file**\n...concise\nonly container instances

+++ Resource allocation
++++_ CPUs, memory,\n...and optionally GPUs
++++ Example
+++++_ 2 container instances\n...1 CPU + 2 CPUs
++++++_ == container group with 3 CPUs


+ Usage <<root>>
--_ support
---_ separate resource requirements
---_ separate teams
++ Divide
+++_ a single functional task\ninto a few container images
++++ Side-car pattern
+++ Examples
++++_ Logging and monitoring
+++++_ Application container
+++++_ Monitoring container (logging)
++++_ multiple apis
+++++_ Frontend container +
+++++_ Backend 3rd party API container\n...(think SigningHub) 

@endmindmap
