@startmindmap "Azure Container Registry"


' https://plantuml.com/theme
!theme sketchy
skinparam backgroundColor #969998

title Azure Container Registry
footer Azure Container Registry

<style>
    mindMapDiagram {
        .root {
            BackgroundColor darkblue
            LineColor black
            FontColor white
        }

        node {
            FontColor white
            LineColor black
            BackgroundColor black
            Shadowing 2.0
            RoundCorner 25
        }
        :depth(0) {
            FontColor black
            LineColor white
            BackgroundColor white
            Shadowing 0.0
        }
        :depth(1) {
            FontColor black
            BackgroundColor darkgrey
            Shadowing 2.0
        }

        arrow {
            LineStyle 4
            LineThickness 0.5
            LineColor green
        }

        boxless {
            FontColor black
            Margin 10
            Padding 10
            MaximumWidth 400
        }
    }
</style>

+ ACR <<root>>
++ Use cases
+++_ Pull images...\nDeploy to...
++++ Scalable orchestration systems
+++++_ Kubernetes, DC/OS, Docker Swarm
++++ Azure services
+++++_ For building\nand running\napplications at scale
++++++_ Azure Kurbernetes Service (AKS)
++++++_ App Service
++++++_ Batch
++++++_ Service Fabric.
+++ Continuous integration and delivery
++++_ Push from...
+++++_ Azure Pipelines
+++++_ Jenkins
-- Service tiers
--- Basic
----_ cost-optimized entry point for developers
--- Standard
----_ Increased storage and image throughput
----_ Suitable for most production scenarios
--- Premium
----_ Highest storage, concurrent operations, and additional features

++ Supported images and artifacts
+++_ Windows and Linux images
+++_ Docker container images
+++_ Content Formats
++++_ Helm charts
++++_ Images built to the OCI Image Format Specification
++ Automated image builds
+++ ACR Tasks <<root>>
++++_ Building, testing, pushing, and deploying images.
++++_ Automatically rebuild application images when base images updated
++++_ Create multi-step tasks (build, test, push, deploy)
+++_ Container OS and framework patching pipeline automation
+++_ Automatic image builds on code commits
-- Storage capabilities
--- Encryption-at-rest
----_ for image data security
--- Regional storage
---- Data Compliance Requirements
----_ ...for data residency and compliance
-----_ Data stored in same region as registry
----_ paired regions if available (or enable geo-replication)
--- Zone redundancy
----_ in the Premium service tier
----_ replication mininum of 3 zones in each enabled region
--- Scalable storage
----_ for repositories, images, layers, and tags
--- Maintenance for Performance
----_ periodic deletion (repos, tags) for maintenance
----_ otherwise performance may be affected

legend right
Azure Container Registry (ACR) is a managed, private Docker registry service
based on the open-source Docker Registry 2.0. Create and maintain Azure 
container registries to store and manage your private Docker container images.
endlegend

@endmindmap
